# Generated by Django 4.1.7 on 2023-03-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_task_completed_at_alter_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('new', 'unassigned'), ('urgent and important', 'urgent and important'), ('not urgent and important', 'urgent and not important'), ('urgent but not important', 'urgent but not important'), ('not urgent and not important', 'not urgent and not important')], default='new', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='todolist.category'),
        ),
    ]
